apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namespace: postgres

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: postgres-ebs

  resources:
    requests:
      storage: 20Gi